name: test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run 🧪
        uses: cypress-io/github-action@v7.4.0
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
      # nyc does not do very strict code coverage
      # the file could be empty and the check would still pass
      - name: check code coverage 📈
        run: npx nyc report --check-coverage --lines 88
      - name: strict code coverage 📊
        run: |
          npx check-coverage App.tsx
          npx check-coverage index.tsx
          npx only-covered App.tsx index.tsx utils.tsx
